In [1]:
# Group members: Richard, Dean, Christoph
import json
from collections import Counter
data = sc.textFile('/FileStore/tables/bje8mjs31493152866609/part_00009-8d8a9')
tweets = data.map(lambda full: (json.loads(full)['text']))

In [2]:
counts = tweets.flatMap(lambda line: line.split(" ")) \
             .map(lambda line: line.lower()) \
             .map(lambda word: (word, 1)) \
             .reduceByKey(lambda a, b: a + b)
                      
top10words = counts.takeOrdered(11, key=lambda a: -a[1])
print "Here is a list of the top 10 words used in tweets: \n", top10words

In [3]:
from collections import Counter
s = tweets.flatMap(lambda line: line.split(":")) \
  .map(lambda line: line.split(" "))
d = s.collect()
lst2 = [item[0] for item in d]

result = Counter(lst2)

Top10 = sorted(result, key=result.get, reverse=True)[:10]

print "These are the top 10 most common words to start a tweet: \n",Top10